baseURL: 'https://sbouts.github.io'
languageCode: en-us
title: Stefan's Notepad
theme: PaperMod

# General Settings
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

# Parameters
params:
  env: production
  description: 'Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod'
  author: Theme PaperMod
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  
  # Home Button
  label:
    text: "Home"
    icon: /img/np.png

# Profile Mode
  profileMode:
    enabled: true
    title: Stefan Bouts
    subtitle: "DevOps Engineer \U0001F468‍\U0001F4BB // Cloud Enthousiast ☁️"
    buttons:
      - name: Notes
        url: notes
      - name: Categories
        url: categories
      - name: Tags
        url: tags
  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/sbouts/'
    - name: github
      url: 'https://github.com/sbouts'
    - name: gitlab
      url: 'https://gitlab.com/sbouts'

# Navbar top
languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Notes
          url: notes
          weight: 5
        - name: Categories
          url: categories
          weight: 10
        - name: Tags
          url: tags
          weight: 15
        - name: Archive
          url: archive
          weight: 20        
        - name: Search
          url: search
          weight: 25

# Minify
minify:
  disableXML: true

# Outputs of search
outputs:
  home:
    - HTML
    - JSON

# Grouping of notes
taxonomies:
  category: categories
  tag: tags

# Privacy Settings
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
